### ISSUE TITLE
can't make comment on latest deployment

### ISSUE THREAD

**Issue by k0vl** [scalableinternetservices/TWO#14]
From eb logs:

I,  INFO -- : Started POST "/whatever_chats/9" for 169.231.183.129 at 2019-11-19 06:43:43 +0000
I,  INFO -- : Processing by CommentsController#create as HTML
I,  INFO -- :   Parameters: {"authenticity_token"=>"Nt6ZcEhdCv15YOQuLd9aIjA2RS1seLslCuUMrOz+KeIzmUv31i++hfHRXbNU+dJWEFIQqQboVHrAiP
qmBLUCaw==", "commentBody"=>"1234", "commit"=>"Post Comment", "id"=>"9"}
W,  WARN -- : Can't verify CSRF token authenticity.
I,  INFO -- : Completed 422 Unprocessable Entity in 1ms (ActiveRecord: 0.0ms | Allocations: 364)
F, FATAL -- : 
ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
actionpack (6.0.0) lib/action_controller/metal/request_forgery_protection.rb:217:in 'handle_unverified_request'
actionpack (6.0.0) lib/action_controller/metal/request_forgery_protection.rb:249:in 'handle_unverified_request'
actionpack (6.0.0) lib/action_controller/metal/request_forgery_protection.rb:244:in 'verify_authenticity_token'
activesupport (6.0.0) lib/active_support/callbacks.rb:429:in 'block in make_lambda'
...
...
...
puma (3.12.1) lib/puma/thread_pool.rb:135:in 'block in spawn_thread'

**Comment by Trevillie** [comment]
Solved.
