### ISSUE TITLE
can't view /whatever

### ISSUE THREAD

**Issue by k0vl** [scalableinternetservices/TWO#17]
I,  INFO -- :  Started GET "/whatever" for 169.231.169.94 at 2019-11-19 19:16:29 +0000
I,  INFO -- :  Processing by WhateverChatsController#index as HTML
D, DEBUG -- :    User Load (0.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
D, DEBUG -- :    Ad Load (0.7ms)  SELECT "ads".* FROM "ads"
I,  INFO -- :  Completed 500 Internal Server Error in 3ms (ActiveRecord: 1.0ms | Allocations: 987)
F, FATAL -- : 
 NoMethodError (undefined method `split' for nil:NilClass):

 app/controllers/whatever_chats_controller.rb:23:in `index'

**Comment by Trevillie** [comment]
Solved.
