### ISSUE TITLE
js not loading

### ISSUE THREAD

**Issue by k0vl** [scalableinternetservices/TWO#19]
I, [2019-11-19T20:45:14.892261 #6881]  INFO -- : [be66a093-0a54-4d29-a677-31e9c8c46a34] Started GET "/packs/js/application-618afa7f882416363feb.js" for 169.231.169.94 at 2019-11-19 20:45:14 +0000
F, [2019-11-19T20:45:14.892933 #6881] FATAL -- : [be66a093-0a54-4d29-a677-31e9c8c46a34]
[be66a093-0a54-4d29-a677-31e9c8c46a34] ActionController::RoutingError (No route matches [GET] "/packs/js/application-618afa7f882416363feb.js"):
[be66a093-0a54-4d29-a677-31e9c8c46a34]
[be66a093-0a54-4d29-a677-31e9c8c46a34] actionpack (6.0.0) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
[be66a093-0a54-4d29-a677-31e9c8c46a34] actionpack (6.0.0) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[be66a093-0a54-4d29-a677-31e9c8c46a34] railties (6.0.0) lib/rails/rack/logger.rb:38:in `call_app'
[be66a093-0a54-4d29-a677-31e9c8c46a34] railties (6.0.0) lib/rails/rack/logger.rb:26:in `block in call'
[be66a093-0a54-4d29-a677-31e9c8c46a34] activesupport (6.0.0) lib/active_support/tagged_logging.rb:80:in `block in tagged'
[be66a093-0a54-4d29-a677-31e9c8c46a34] activesupport (6.0.0) lib/active_support/tagged_logging.rb:28:in `tagged'
[be66a093-0a54-4d29-a677-31e9c8c46a34] activesupport (6.0.0) lib/active_support/tagged_logging.rb:80:in `tagged'
[be66a093-0a54-4d29-a677-31e9c8c46a34] railties (6.0.0) lib/rails/rack/logger.rb:26:in `call'
[be66a093-0a54-4d29-a677-31e9c8c46a34] actionpack (6.0.0) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[be66a093-0a54-4d29-a677-31e9c8c46a34] actionpack (6.0.0) lib/action_dispatch/middleware/request_id.rb:27:in `call'
[be66a093-0a54-4d29-a677-31e9c8c46a34] rack (2.0.7) lib/rack/method_override.rb:22:in `call'
[be66a093-0a54-4d29-a677-31e9c8c46a34] rack (2.0.7) lib/rack/runtime.rb:22:in `call'
[be66a093-0a54-4d29-a677-31e9c8c46a34] activesupport (6.0.0) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
[be66a093-0a54-4d29-a677-31e9c8c46a34] actionpack (6.0.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
[be66a093-0a54-4d29-a677-31e9c8c46a34] rack (2.0.7) lib/rack/sendfile.rb:111:in `call'
[be66a093-0a54-4d29-a677-31e9c8c46a34] actionpack (6.0.0) lib/action_dispatch/middleware/host_authorization.rb:77:in `call'
[be66a093-0a54-4d29-a677-31e9c8c46a34] railties (6.0.0) lib/rails/engine.rb:526:in `call'
[be66a093-0a54-4d29-a677-31e9c8c46a34] puma (3.12.1) lib/puma/configuration.rb:227:in `call'
[be66a093-0a54-4d29-a677-31e9c8c46a34] puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
[be66a093-0a54-4d29-a677-31e9c8c46a34] puma (3.12.1) lib/puma/server.rb:474:in `process_client'
[be66a093-0a54-4d29-a677-31e9c8c46a34] puma (3.12.1) lib/puma/server.rb:334:in `block in run'
[be66a093-0a54-4d29-a677-31e9c8c46a34] puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'

**Comment by Trevillie** [comment]
Is it running now? Please close if this is the same issue we solved during lab.
